fleamarket_00/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^shop/', include('shop.urls', namespace='shop')),
    url(r'^user/', include('profiles.urls', namespace='profiles')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^summernote/', include('django_summernote.urls')),
    url(r'^login/', 'django.contrib.auth.views.login', name='login', kwargs={'template_name': 'login.html'}),
    url(r'^logout/', 'django.contrib.auth.views.logout',name='logout', kwargs={'next_page': '/login/'}),
    url(r'^register/', 'fleamarket_00.views.register', name='register'),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

profiles/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # url(r'^item/(?P<item_id>[0-9]+)$', 'shop.views.item_detail', name='item_detail'),
    url(r'^(?P<user_id>[0-9]+)/$', views.profile, name='profile'),
]

shop/urls.py
from django.conf.urls import url

urlpatterns = [
    url(r'^$',                              'shop.views.index',       name='index'),
    url(r'^item/(?P<item_id>[0-9]+)$',      'shop.views.item_detail', name='item_detail'),
    url(r'^item/new$',                      'shop.views.item_new',    name='item_new'),
    url(r'^item/(?P<item_id>[0-9]+)/edit$', 'shop.views.item_edit',   name='item_edit'),
    url(r'^comment$',                       'shop.views.comment',     name='comment'),
]

profiles/models.py
from django.db import models

# Create your models here.

profiles/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import get_user_model
from bs4 import BeautifulSoup

User = get_user_model()

def profile(request, user_id):
    user = get_object_or_404(User, id=user_id)
    items_of_user = user.item_set.order_by('-created_at')

    for item in items_of_user:
        soup = BeautifulSoup(item.desc, "html.parser")
        try:
            item.img_url = soup.find('img')['src']
        except:
            pass
    context = {
        'user':request.user,
        'items_of_user':items_of_user,
    }

    return render(request, 'profile.html', context)

profiles/templates/profile.html
{% extends 'shop/base.html' %}
{% load humanize %}

{% block content %}
<h3>프로필 페이지</h3>

<div class="item-list">
    {% for item in items_of_user %}
        <a class="item-card" href="{% url 'shop:item_detail' item.pk %}">
{#            <div class="yu-thumb-img" style="background-image: url('{{ item.photos_of_item.all.0.image.url }}')"></div>#}
            <img src="{{ item.photos_of_item.all.0.image.url }}" alt=""/>
            <div class="item-card-content">
                <span class="name"> {{ item.name }} </span> <br/>
                <span class="price">{{ item.price | intcomma }}<span class="yu-won">원</span></span>
            </div>
        </a>
    {% empty %}
        <li>게시한 사진이 없습니다.</li>
    {% endfor %}
</div>
{% endblock %}