fleamarket_00/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^shop/', include('shop.urls', namespace='shop')),
    url(r'^user/', include('profiles.urls', namespace='profiles')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^summernote/', include('django_summernote.urls')),
    url(r'^login/', 'django.contrib.auth.views.login', name='login', kwargs={'template_name': 'login.html'}),
    url(r'^logout/', 'django.contrib.auth.views.logout',name='logout', kwargs={'next_page': '/login/'}),
    url(r'^register/', 'fleamarket_00.views.register', name='register'),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

profiles/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # url(r'^item/(?P<item_id>[0-9]+)$', 'shop.views.item_detail', name='item_detail'),
    url(r'^(?P<user_id>[0-9]+)/$', views.profile, name='profile'),
]

shop/urls.py
from django.conf.urls import url

urlpatterns = [
    url(r'^$',                              'shop.views.index',       name='index'),
    url(r'^item/(?P<item_id>[0-9]+)$',      'shop.views.item_detail', name='item_detail'),
    url(r'^item/new$',                      'shop.views.item_new',    name='item_new'),
    url(r'^item/(?P<item_id>[0-9]+)/edit$', 'shop.views.item_edit',   name='item_edit'),
    url(r'^comment$',                       'shop.views.comment',     name='comment'),
]

shop/models.py
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)
from django.core.urlresolvers import reverse_lazy
from django.conf import settings
from django_summernote import models as summer_models
from django_summernote import fields as summer_fields

CONDITION_OF_ITEM = (
    ('S', '아직 미개봉'),
    ('A', '거의 새것'),
    ('B', '사용감 있음'),
    ('C', '오래됨'),
)

WAY_OF_DEAL = (
    ('direct', '직거래'),
    ('ship', '택배'),
)

STATE_OF_ITEM = {
    ('sold', '판매완료'),
    ('sale', '판매중'),
}

class Category(models.Model):
    name = models.CharField('카테고리 이름', max_length=100)

    def __str__(self):
        return self.name


class ItemManager(models.Manager):
    pass

class Item(models.Model):

    vendor = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='판매자')
    category = models.ForeignKey(Category, verbose_name='카테고리')
    created_at = models.DateTimeField('등록일', auto_now_add=True)
    updated_at = models.DateTimeField('수정일', auto_now=True)
    name = models.CharField('이름', max_length=200)
    deal_place = models.CharField('거래장소', max_length=10, null=True, blank=True)
    include_shipping = models.BooleanField('배송료포함', default=False, blank=True)
    deal_way = models.CharField('거래방법', max_length=6, choices=WAY_OF_DEAL, default='direct', null=False, blank=False)
    condition = models.CharField('물품상태', max_length=1, choices=CONDITION_OF_ITEM, default='B', null=False, blank=False)
    desc = models.TextField('설명', null = False, max_length=1000)
    price = models.CommaSeparatedIntegerField('판매가', max_length=10, default=10000)
    state = models.CharField('판매여부', max_length=4, choices=STATE_OF_ITEM, default='sale', null=False, blank=False)

    objects = ItemManager()


    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse_lazy('shop:item_detail', kwargs={'item_id':self.id})

class ItemPhoto(models.Model):
    item = models.ForeignKey(Item, related_name='photos_of_item')
    image = models.ImageField(upload_to='%Y%m%d')

    def delete(self, *args, **kwargs):
        self.image.delete()
        super(ItemPhoto, self).delete(*args, **kwargs)

class ItemComment(models.Model):
    body = models.CharField('코멘트', max_length=300)
    created_at = models.DateTimeField('등록일', auto_now_add=True)
    updated_at = models.DateTimeField('수정일', auto_now=True)
    item = models.ForeignKey(Item, related_name='comments')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='comments')


class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            email,
            password=password,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class CustomUser(AbstractBaseUser):
    email = models.EmailField(
        verbose_name='이메일',
        max_length=255,
        unique=True,
    )

    nickname = models.CharField('별명', max_length=20, unique=True)

    STATES_OF_CREDIBILITY = (
        ('vendor', '거상'),
        ('pro', '프로'),
        ('newbie', '뉴비'),
    )

    credibility = models.CharField(max_length=10,
                                   choices=STATES_OF_CREDIBILITY,
                                   default='newbie')

    joined_at = models.DateTimeField('가입일', auto_now_add=True)

    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'

    def get_full_name(self):
        # The user is identified by their email address
        return self.email

    def get_short_name(self):
        # The user is identified by their email address
        return self.email

    def get_nickname(self):
        return self.nickname

    def __str__(self):              # __unicode__ on Python 2
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

shop/forms.py
from django import forms
from django.forms.formsets import BaseFormSet
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.contrib.auth import get_user_model

from .models import CustomUser, Item, Category, ItemPhoto
from .models import CONDITION_OF_ITEM, WAY_OF_DEAL


from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget


User = get_user_model()

# # Apply summernote to specific fields.
# class SomeForm(forms.Form):
#     foo = forms.CharField(widget=SummernoteWidget())  # instead of forms.Textarea

class ItemPhotoForm(forms.ModelForm):

    class Meta:
        model = ItemPhoto
        exclude = ('item',)

class ItemForm(forms.ModelForm):

    category = forms.ModelChoiceField(widget=forms.HiddenInput(),
                                          queryset=Category.objects.all())

    vendor = forms.ModelChoiceField(widget=forms.HiddenInput(),
                                    queryset=User.objects.all())

    state = forms.CharField(widget=forms.HiddenInput())

    deal_way = forms.ChoiceField(required=True, widget=forms.RadioSelect, choices=WAY_OF_DEAL)

    condition = forms.ChoiceField(required=True, widget=forms.RadioSelect, choices=CONDITION_OF_ITEM)

    price = forms.CharField( widget= forms.TextInput(attrs={'type':'text',  'maxlength':'10', 'pattern': '\d*'},))

    # shipping_price = forms.CharField( widget= forms.TextInput(attrs={'type':'number', 'min':0}))

    def __init__(self, *args, **kwargs):
        super(ItemForm, self).__init__(*args, **kwargs)

        for field in self.fields.values():
            field.error_messages = {
                'required': '*입력된 정보가 없습니다.',
                'invalid': '*잘못된 정보입니다. 다시 입력해주세요.'
            }

    class Meta:
        model = Item
        exclude = ('created_at', 'updated_at', )



class UserCreationForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = CustomUser
        fields = ('email', 'nickname')

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = CustomUser
        fields = ('email', 'password', 'nickname', 'is_active', 'is_admin')

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]

# class ItemPhotoFormset(BaseFormSet):
#
#

shop/views.py
from django.shortcuts import render, render_to_response, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.forms import inlineformset_factory
from django.http import HttpResponse

from .models import Item, Category, ItemPhoto, ItemComment
from .forms import ItemForm
from django.template import loader

from time import strftime

import json

User = get_user_model()


# Create your views here.
def index(request):
    item_list = Item.objects.order_by('-created_at')[:50]

    context = {
        'item_list' : item_list,
        'user': request.user,
    }

    return render_to_response('shop/index.html', context)

def item_detail(request, item_id):

    item = Item.objects.get(pk=item_id)

    context = {
        'item' : item,
        'user': request.user
    }

    return render(request, 'shop/item_detail.html', context)


@login_required()
def item_edit(request, item_id):

    before_item = Item.objects.get(id=item_id)
    is_vendor = (request.user == before_item.vendor)

    if is_vendor:
        ItemPhotoFormSet = inlineformset_factory(Item, ItemPhoto, fields=('image',), can_delete=False, extra=8)

        if request.method == "GET":

            initial_data = {
                'category': before_item.category,
                'state':before_item.state,
                'photos_of_item': before_item.photos_of_item,
                'vendor': before_item.vendor,
                'name': before_item.name,
                'include_shipping': before_item.include_shipping,
                'price': before_item.price,
                'desc': before_item.desc,
                'deal_place': before_item.deal_place,
                'deal_way': before_item.deal_way,
                'condition': before_item.condition
            }

            item_form = ItemForm(initial=initial_data)
            item = Item()
            item_photo_formset = ItemPhotoFormSet(instance=item)

        if request.method == "POST":
            item_form = ItemForm(data=request.POST)
            item = Item()
            item_photo_formset = ItemPhotoFormSet(instance=item)

            if item_form.is_valid():

                new_item = item_form.save(commit=False)
                new_item.vendor = request.user

                item_photo_formset = ItemPhotoFormSet(request.POST, request.FILES, instance = new_item)

                if item_photo_formset.is_valid():
                    new_item.save()
                    item_photo_formset.save()

                    return redirect(new_item.get_absolute_url())

                else:
                    print(item_photo_formset.errors)

            else:
                print("item_form is_valid is not true")
                print(item_form.errors)

        context = {
            'item_form': item_form,
            'item_photo_formset': item_photo_formset,
            'user': request.user,
            'title': '물품수정'
        }

    else:
        return redirect('shop:item_detail', item_id)

    return render(request, 'shop/item_form.html', context)

@login_required()
def comment(request):
    response_data = {}

    if request.method == 'POST':

        if request.POST.get('body') == None:
            comment_id = request.POST.get('comment')
            i_comment = ItemComment.objects.get(id=comment_id)
            i_comment.delete()

            response_data['status'] = "this isn't happening"

        else:

            body = request.POST.get('body')
            item_id = request.POST.get('item')
            user_id = request.POST.get('user')
            item = Item.objects.get(id=item_id)
            user = User.objects.get(id=user_id)

            comment = ItemComment(body=body, item=item, user=user)
            comment.save()

            template = loader.get_template('shop/comment.html')

            response_data['comment'] = template.render({
                'item_comment':ItemComment.objects.filter(id=comment.id),
                'user':request.user
            })

    else:
        response_data['nothing to see'] = "this isn't happening"

    return HttpResponse(json.dumps(response_data), content_type="application/json")


@login_required
def item_new(request):

    ItemPhotoFormSet = inlineformset_factory(Item, ItemPhoto, fields=('image',), can_delete=False, extra=8)

    if request.method == "GET":

        initial_data = {
            'category': Category.objects.get(name="판매"),
            'state':'sale',
            'vendor': request.user,
            'name': strftime("%m-%d %H:%M:%S의 테스트 아이템"),
            'purchased_at': "최근",
            'shipping_price': "3000",
            'desc': "이것은 설명입니다.",
            'deal_place': "우리집",
            'deal_way': "direct",
            'condition': "S"
        }

        item_form = ItemForm(initial=initial_data)
        item = Item()
        item_photo_formset = ItemPhotoFormSet(instance=item)

    if request.method == "POST":
        item_form = ItemForm(data=request.POST)
        item = Item()
        item_photo_formset = ItemPhotoFormSet(instance=item)

        if item_form.is_valid():

            new_item = item_form.save(commit=False)
            new_item.vendor = request.user

            item_photo_formset = ItemPhotoFormSet(request.POST, request.FILES, instance = new_item)

            if item_photo_formset.is_valid():
                new_item.save()
                item_photo_formset.save()

                return redirect(new_item.get_absolute_url())

            else:
                print(item_photo_formset.errors)

        else:
            print("item_form is_valid is not true")
            print(item_form.errors)

    context = {
        'item_form': item_form,
        'item_photo_formset': item_photo_formset,
        'user': request.user,
        'title': '물품등록'
    }

    return render(request, 'shop/item_form.html', context)

shop/templates/shop/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/dist/css/bootstrap.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'shop/style.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'font-awesome/css/font-awesome.css' %}"/>
    <script type="text/javascript" src="{% static 'jquery/dist/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'bootstrap/dist/js/bootstrap.js' %}"></script>
</head>
<body>

<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'shop:index' %}">
                <strong>YU 4080</strong>
            </a>
        </div>
        <ul class="nav navbar-nav navbar-right">
            {% if not user.is_authenticated %}
                <li class="dropdown"><a href="{% url 'login' %}">로그인</a></li>
            {% else %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ user.get_nickname }} <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'logout' %}">로그아웃</a></li>
                        <li><a href="{% url 'profiles:profile' user.id %}">내정보</a></li>
                    </ul>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

<div class="main container">
    {% block content %}
    {% endblock %}
</div>

<footer>

</footer>

<div class="yu-fixed-btn">
    <a class="yu-circle-btn" href="{% url 'shop:item_new' %}" data-toggle="tooltip" data-placement="top" title="판매하기">
        <i class="fa fa-plus fa-3x"></i>
    </a>
</div>

<script type="text/javascript">
    (function() {
        $('a.yu-circle-btn').tooltip();
    })();
</script>

</body>
</html>

shop/templates/shop/item_detail.html
{% extends "shop/base.html" %}
{% load humanize %}
{% load shop_tags %}

{% block content %}
{% if item %}
    <div class="item-detail-container">
        <div class="middle-info-area">
            <div class="item-img-area">
                <div class="item-img-preview">
                    <img src="" alt=""/>
                </div>
                <div class="item-imgs">
                {% for photo in item.photos_of_item.all %}
                    <div class="img-box">
                        <img src="{{ photo.image.url }}"/>
                    </div>
                {% endfor %}
                </div>
            </div>
            <div class="item-info-area">
                <div class="top">
                    <span class="label label-primary">{{ item.get_condition_display }}</span>
                    <span class="label label-info">{{ item.get_deal_way_display }}</span>
                    {% if item.vendor.id == user.id %}
                        <a style="color:red" href="{% url 'shop:item_edit' item.id %}">수정하기</a>
                    {% endif %}
                    <h5>{{ item.name }}</h5>
                    {% if item.include_shipping %}
                        <span class="include-shipping">배송료포함</span>
                    {% endif %}
                    <span class="price"><strong>{{ item.price | intcomma }}원</strong></span>
                    <span class="kor-timesince">{{ item.created_at | get_due_date_string}}</span>
                </div>
                <hr/>
                <div class="middle">
                    {% if item.deal_way == 'direct' %}
                        <span class="info-label">거래장소</span>
                        <p class="info-content">{{ item.deal_place }}</p>
                    {% endif %}
                </div>
                <hr/>
                <div class="bottom">
                    <span class="info-label">판매자정보</span>
                    <p class="info-content">{{ item.vendor.get_nickname }}</p>
                </div>
            </div>
        </div>
        <div class="bottom-info-area">
            <div class="item-desc-area">
                <div class="info-label">제품설명</div>
                {{ item.desc }}
            </div>
            <hr/>
            <div class="item-comment-area">
                <form action="{% url 'shop:comment' %}" method="post" id="comment-form" enctype="multipart/form-data">
                    {% csrf_token %}
                    <input type="hidden" id="item" name="item" value="{{ item.id }}"/>
                    <input type="hidden" id="user" name="user" value="{{ user.id }}"/>
                    <textarea name="body" id="comment" rows="10"></textarea>
                    <input type="submit" value="댓글등록"/>
                </form>
            </div>
            <div id="comment-list">
                {% include 'shop/comment.html' %}
            </div>
        </div>
    </div>
{% else %}
    <p>존재하지 않는 아이템입니다.</p>
{% endif %}

<script type="text/javascript">
    (function() {
        $(document).ready(function() {
            var selectedItemImg = $('.item-img-preview img');
            var imgSrc = $('.item-imgs > .img-box img').attr('src');
            var csrftoken = getCookie('csrftoken');

            selectedItemImg.attr('src', imgSrc);

            $('.item-imgs .img-box').click(function() {
                var imgSrc = $(this).find('img').attr('src');
                selectedItemImg.attr('src', imgSrc);
            });

            $('#comment-form').on('submit', function(event) {
                event.preventDefault();
                console.log("form submitted");
                comment_new();
            });

            addListener();

            function delete_comment(fromBtn) {
                $.ajax({
                    url:'/shop/comment',
                    type:'POST',
                    data:{
                        comment:$(fromBtn).find('.comment_id').val(),
                        csrfmiddlewaretoken:csrftoken
                    },
                    success:function(response) {
                        console.log("Delete Success!");
                        $("#comment_"+$(fromBtn).find('.comment_id').val()).remove();
                        console.log(response);
                    },
                    error:function(response, err) {
                        console.log("Delete Error");
                        console.log(response);
                    }

                })
            }


            function comment_new(){
                console.log("new comment!");
                $.ajax({
                    url:'/shop/comment',
                    type:'post',
                    data:{
                        item:$('#item').val(),
                        user:$('#user').val(),
                        body:$('#comment').val(),
                        csrfmiddlewaretoken:$('input[name="csrfmiddlewaretoken"]').val()
                    },
                    success:function(response) {
                        $('#comment').val('');
                        $('#comment-list').prepend(response.comment)
                        console.log("Success!");
                        console.log(response);
                        addListener();
                    },
                    error:function(response, err) {
                        console.log("Error");
                        console.log(response);
                    }
                })
            }

            function addListener() {
                $('.del-comment-btn').on('click', function(event) {
                    delete_comment(this);
                });
            }

            function getCookie(name) {
                var cookieValue = null;
                if (document.cookie && document.cookie != '') {
                    var cookies = document.cookie.split(';');
                    for (var i = 0; i < cookies.length; i++) {
                        var cookie = jQuery.trim(cookies[i]);
                        // Does this cookie string begin with the name we want?
                        if (cookie.substring(0, name.length + 1) == (name + '=')) {
                            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                            break;
                        }
                    }
                }
                return cookieValue;
            }
        });
    })();
</script>

{% endblock %}

shop/templates/shop/item_form.html
{% extends "shop/base.html" %}

{% block content %}

<div class="white-background">
    <div class="item-form-container">

        <h3>{{ title }}</h3>

        <hr/>

        <form method="post" action="{% url 'shop:item_new' %}" enctype="multipart/form-data">
            {% csrf_token %}

            <div>{{ item_form.category }}</div>
            <div>{{ item_form.vendor }}</div>
            <div>{{ item_form.state }}</div>

            {{ item_photo_formset.management_form }}
            <div class="yf-input img-upload-area">
                <div id="item-img-container">
                    <div class="item-img-wrapper"><i class="fa fa-picture-o fa-2x"></i></div>
                    <div class="item-img-wrapper"><i class="fa fa-picture-o fa-2x"></i></div>
                    <div class="item-img-wrapper"><i class="fa fa-picture-o fa-2x"></i></div>
                    <div class="item-img-wrapper"><i class="fa fa-picture-o fa-2x"></i></div>
                    <div class="item-img-wrapper"><i class="fa fa-picture-o fa-2x"></i></div>
                    <div class="item-img-wrapper"><i class="fa fa-picture-o fa-2x"></i></div>
                    <div class="item-img-wrapper"><i class="fa fa-picture-o fa-2x"></i></div>
                    <div class="item-img-wrapper"><i class="fa fa-picture-o fa-2x"></i></div>
                </div>
                {% for photo_form in item_photo_formset %}
                    <div class="hidden-img-upload">
                        {{ photo_form.image }}
                    </div>
                {% endfor %}
            </div>

            <div class="yf-input">
                <label for="{{ item_form.name.id_for_label }}">상품이름</label>
                {{ item_form.name }}
                <div class="yf-error-msg">
                    {{ item_form.name.errors }}
                </div>
            </div>

            <div class="yf-input deal-way">
                <label for="{{ item_form.deal_way.id_for_label }}">거래방법</label>
                {% for radio in item_form.deal_way %}
                    <div class="radio-btn">
                        {{ radio }}
                    </div>
                {% endfor %}
                <div class="yf-error-msg">
                    {{ item_form.deal_way.errors }}
                </div>
            </div>

            <div class="yf-input condition">
                <label for="{{ item_form.condition.id_for_label }}">옷 상태</label>
                {% for radio in item_form.condition %}
                    <div class="radio-btn">
                        {{ radio }}
                    </div>
                {% endfor %}
                <div class="yf-error-msg">
                    {{ item_form.condition.errors }}
                </div>
            </div>

            <div class="yf-input deal-place">
                <label for="{{ item_form.deal_place.id_for_label }}">거래장소</label>
                {{ item_form.deal_place }}
                <div class="yf-error-msg">
                    {{ item_form.deal_place.errors }}
                </div>
            </div>

            <div class="yf-input price">
                <label for="{{ item_form.price.id_for_label }}">가격</label>
                {{ item_form.price }}
                <div class="yf-error-msg">
                    {{ item_form.price.errors }}
                </div>
            </div>

            <div class="yf-input include_shipping">
                <label for="{{ item_form.include_shipping.id_for_label }}">배송비포함</label>
                {{ item_form.include_shipping }}
                <div class="yf-error-msg">
                    {{ item_form.include_shipping.errors }}
                </div>
            </div>

            <div class="yf-input desc">
                <label for="{{ item_form.desc.id_for_label }}">설명</label>
                {{ item_form.desc }}
                <div class="yf-error-msg">
                    {{ item_form.desc.errors }}
                </div>
            </div>

            <hr/>

            <div class="yf-input-btns">
                <input class="" type="submit" value="완료"/>
                <a href="{{request.META.HTTP_REFERER}}">취소</a>
            </div>

        </form>
    </div>
</div>

<script type="text/javascript">

    (function() {
        $(document).ready(function(){

            var UPLOADED_IMG = 0;
            var itemImgContainer = $('#item-img-container');
            var itemImgWrapper = itemImgContainer.find('.item-img-wrapper');

            $('.img-upload-area .hidden-img-upload input').each(function() {
                $(this).on('change', function() {

                    if(window.FileReader){
                        //image 파일만
                        if (! $(this)[0].files[0].type.match(/image\//) ) return;

                        var reader = new FileReader();
                        reader.onload = function(e){

                            var src = e.target.result;
                            var curItemImgWrapper = itemImgContainer.find('div.item-img-wrapper:nth-child(' + (++UPLOADED_IMG) + ')');

                            curItemImgWrapper.find('i').remove();
                            curItemImgWrapper.append('<img src="'+src+'" class="upload-thumb">');
                        };
                        reader.readAsDataURL($(this)[0].files[0]);
                    }

                    {#                else { // old IE#}
                    {#                    console.log("주석??");#}
                    {#                    $(this)[0].select();#}
                    {#                    $(this)[0].blur();#}
                    {#                    var imgSrc = document.selection.createRange().text;#}
                    {#                    parent.prepend('<div class="upload-display"><div class="upload-thumb-wrap"><img class="upload-thumb"></div></div>');#}
                    {##}
                    {#                    var img = $(this).siblings('.upload-display').find('img');#}
                    {#                    img[0].style.filter = "progid:DXImageTransform.Microsoft.AlphaImageLoader(enable='true',sizingMethod='scale',src=\""+imgSrc+"\")";#}
                    {#                }#}
                });
            });

            itemImgWrapper.each(function () {
                $(this).click(function(){
                    $('#id_photos_of_item-'+UPLOADED_IMG+'-image').click();
                });
            });

            $(".yf-input.deal-way").change(function() {
                var deal_way = $(this).find(".radio-btn input:checked").val();

                if(deal_way == "ship") {
                    $(".yf-input.shipping-checkbox").show();
                    $(".yf-input.deal-place").hide();
                } else {
                    $(".yf-input.shipping-checkbox").hide();
                    $(".yf-input.deal-place").show();
                }
            });
        });
    })();
</script>

{% endblock %}